@startuml

class MasterHiggins

class Hacha
class Fuego
MasterHiggins o-- Hacha
Hacha --> Fuego

class Patineta
MasterHiggins o-- Patineta

class Fruta
class Manzana
class Banana
class Uva
class Tomate
class Zanahoria

Fruta <|-- Manzana
Fruta <|-- Banana
Fruta <|-- Uva
Fruta <|-- Tomate
Fruta <|-- Zanahoria

MasterHiggins o-- Fruta

class Huevo
class Angel
MasterHiggins o-- Huevo
Huevo --> Hacha
Huevo --> Patineta
Huevo --> Angel

class Enemigo
class Caracol
class Murcielago
class Serpiente
class Roca
class JefeFinal

Enemigo <|-- Caracol
Enemigo <|-- Murcielago
Enemigo <|-- Serpiente
Enemigo <|-- Roca
Enemigo <|-- JefeFinal

MasterHiggins -- Enemigo

class PrincesaTina
MasterHiggins --> PrincesaTina

class Energia
class BarraEnergia
MasterHiggins o-- Energia
Energia -- BarraEnergia

class Puntos
class Bonus
MasterHiggins o-- Punto
Bonus --> Punto

class JefeMundo1
class JefeMundo2
class JefeMundo3
class JefeMundo4

JefeFinal <|-- JefeMundo1
JefeFinal <|-- JefeMundo2
JefeFinal <|-- JefeMundo3
JefeFinal <|-- JefeMundo4

class Nivel
class Mundo
class Tiempo

Mundo o-- Nivel
Nivel o-- Enemigo
Nivel o-- Fruta
Nivel o-- Tiempo

@enduml
