@startuml

class Mundo{
-Numero
+Iniciar()
}

class Nivel{
-Numero 
+Comenzar()
}

class Tiempo{
-TiempoRestante
+DisminuirTiempo()
}

class Energia{
-NivelEnergiaActual
+AumentarEneria()
+DisminuirEnergia()
}

class Punto{
-Valor
+AgregarPuntos()
+VerificarVidaExtra()
}


class Jugador

class MasterHiggins{
-Energia
-AgregarPuntos
+Mover()
+Atacar()
+UsarItem()
}

class Princesa{
+SerRescatada()
}

class Item{
+Usar()
}

class Fruta{
+DarPuntos()
}

class Manzana
class Banana
class Uva
class Tomate
class Zanahoria

class Huevo{
+Romper()
}

class Hacha{
+Lanzar()
}

class Angel{
+Darinvensibilidad()
}

class Patineta{
+AumentarVelocidad()
}

class Fuego{
+QuemarEnemigos()
}

class Bebida{
+RecuperarEnergia()
}


class Enemigo{
-Vida
+Atacar()
+Seratacado()
{


class Caracol
class Murcielago
class Serpiente
class Roca


class JefeFinal{
+AtacarEspecialmente()
}

class JefeMundoUno
class JefeMundoDos
class JefeMundoTres
class JefeMundoCuatro

MasterHiggins --|> Jugador

Fruta --|> Item
Huevo --|> Item
Hacha --|> Item
Angel --|> Item
Patineta --|> Item
Fuego --|> Item
Bebida --|> Item

Manzana --|> Fruta
Banana --|> Fruta
Uva --|> Fruta
Tomate --|> Fruta
Zanahoria --|> Fruta

Caracol --|> Enemigo
Murcielago --|> Enemigo
Serpiente --|> Enemigo
Roca --|> Enemigo
JefeFinal --|> Enemigo

JefeMundoUno --|> JefeFinal
JefeMundoDos --|> JefeFinal
JefeMundoTres --|> JefeFinal
JefeMundoCuatro --|> JefeFinal

Mundo "1" *-- "1..8" Nivel
Nivel "1" *-- "1" Tiempo
Nivel "1" *-- "1" Energia

Nivel "1" o-- "*" Enemigo
Nivel "1" o-- "*" Item


MasterHiggins "1" -- "1" Energia
MasterHiggins "1" -- "1" Punto
MasterHiggins "1" o-- "*" Item


@enduml